import { Fetch as fetchDepartments } from "../store/HR/Setup/Department";
import { Fetch as fetchPositions } from "../store/HR/Setup/Position";
import { Fetch as fetchPositionLevels } from "../store/HR/Setup/PositionLevel";
import { Fetch as fetchEntryTypeNames } from "../store/HR/Setup/EntryTypeNames";
import { Fetch as fetchNationalities } from "store/HR/Setup/Nationality";
import { Fetch as fetchLanguages } from "store/HR/Setup/Language";
import { Fetch as fetchEmployeeStatuses } from "store/HR/Setup/EmployeeStatus";
import { Fetch as fetchEmployees } from "../store/HR/ResourceManagement/Employee";
import { Fetch as fetchQualificationTypes } from "store/HR/Setup/QualificationType";
import { Fetch as fetchEducationTypes } from "store/HR/Setup/EducationType";
import { Fetch as fetchInstitutions } from "store/HR/Setup/Institution";
import { Fetch as fetchDisciplinaryActionTypes } from "store/HR/Setup/DisciplinaryActionType";
import { Fetch as fetchLeaveTypes } from "store/HR/Setup/LeaveType";
import { Fetch as fetchTerminationTypes } from "store/HR/Setup/TerminationType";
import { Fetch as fetchTrainingTypes } from "store/HR/Setup/TrainingType";
import { Fetch as fetchCertificationTypes } from "store/HR/Setup/CertificationType";
export default () => (dispatch) => {
  dispatch(fetchDepartments());
  dispatch(fetchPositions());
  dispatch(fetchPositionLevels());
  dispatch(fetchEntryTypeNames());
  dispatch(fetchNationalities());
  dispatch(fetchLanguages());
  dispatch(fetchEmployeeStatuses());
  dispatch(fetchEmployees());
  dispatch(fetchQualificationTypes());
  dispatch(fetchEducationTypes());
  dispatch(fetchInstitutions());
  dispatch(fetchDisciplinaryActionTypes());
  dispatch(fetchLeaveTypes());
  dispatch(fetchTerminationTypes());
  dispatch(fetchTrainingTypes());
  dispatch(fetchCertificationTypes());
};
