import { Fetch as fetchAccountTypes } from "../store/GeneralSetup/AccountTypes";
import { Fetch as fetchCities } from "../store/GeneralSetup/Cities";
import { Fetch as fetchCountries } from "../store/GeneralSetup/Countries";
import { Fetch as fetchCurrencies } from "../store/GeneralSetup/Currencies";
import { Fetch as fetchRegions } from "../store/GeneralSetup/Regions";
import { Fetch as fetchCompanies } from "../store/GeneralSetup/Company";
import { Fetch as fetchBanks } from "../store/Finance/MasterData/Bank";
import { Fetch as fetchChartOfAccounts } from "../store/Finance/MasterData/ChartsOfAccounts/chartOfAccounts";
import { Fetch as fetchItemCategories } from "../store/Inventory/Setup/Item/Item_Categories";
import { Fetch as fetchVendorPostingGroups } from "../store/GeneralSetup/Posting/Vendor_Posting_Group";
import { Fetch as fetchVATPostingGroups } from "../store/GeneralSetup/Posting/VAT_Posting_Group";
import { Fetch as fetchCustomerPostingGroups } from "../store/GeneralSetup/Posting/CustomerPostingGroups";
import { Fetch as fetchVendors } from "../store/Finance/PurchaseProcess/Vendors";
import { Fetch as fetchGeneralLedgerEntries } from "../store/Finance/LedgerEntries/GeneralLedgers";
import { Fetch as fetchPurchaseLedgerEntries } from "../store/Finance/LedgerEntries/PurchaseLedgerEntries";
import { Fetch as fetchSalesLedgerEntries } from "../store/Finance/LedgerEntries/SalesLedgerEntries";
import { Fetch as fetchUOMs } from "../store/Inventory/Setup/UOM/";
import Warehouse from "./Warehouse";
import Finance from "./Finance";
import General from "./General";
import Purchase from "./Purchase";
import Sales from "./Sales";
import HR from "./HR";

export const loadPermissions = () => (dispatch) => {
  dispatch(fetchAccountTypes());
  dispatch(fetchCities());
  dispatch(fetchCountries());
  dispatch(fetchCurrencies());
  dispatch(fetchRegions());
  dispatch(fetchCompanies());
  dispatch(fetchBanks());
  dispatch(fetchChartOfAccounts());
  dispatch(fetchVendors());
  dispatch(fetchItemCategories());
  dispatch(fetchVendorPostingGroups());
  dispatch(fetchCustomerPostingGroups());
  dispatch(fetchVATPostingGroups());
  dispatch(fetchGeneralLedgerEntries());
  dispatch(fetchPurchaseLedgerEntries());
  dispatch(fetchSalesLedgerEntries());
  // Inventory
  dispatch(fetchUOMs());
  dispatch(Warehouse());
  dispatch(Finance());
  dispatch(General());
  dispatch(Purchase());
  dispatch(Sales());
  dispatch(HR());
};
